### ISSUE TITLE
p2p code review

### ISSUE THREAD

**Issue by dili021** [dili021/ticTacToe#1]

**Comment by Kyle-Law** [comment]
Great job for putting an extra mile to remake a new tictactoe project to reinforce your understanding. Overall the game functioned well, I'm particularly drawn by how you randomize the wordings each round. The single responsibility principle is also executed 👍 

Not sure but I guess the `class Game` should be placed in the `lib` folder as a separate file?

**Comment by patriciachrysy** [comment]
Good job refactoring @dili021. I will just have a minors remark: you can completely move the game class of the main file and put it into its own file that you'll just call in the main.

**Comment by nyatindopatrick** [comment]
All said I have no more remarks. Good work
